version: '3'

services:
  db:
    container_name: mariadb
    build: ./requirements/mariadb/.
    restart: unless-stopped #always
    env_file: ../.env
    environment:
      - 
    volumes:
      - db_data:/var/lib/mysql
#    command:
    networks: inception

  wordpress:
    depends_on:
      - db
  container_name: wordpress
  build: ./requirements/wordpress
  ports:
    - 
  restart: always
  env_file : ../.env
  environment:
    - WORDPRESS_DB_HOST=db:3306
    - WORDPRESS_DB_USER=$MYSQL_USER
    - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    - WORDPRESS_DB_NAME=wordpress
  volumes:
    - wordpress:/var/www/html


#volumes:
#  db_data: {}