version: '3.8'
  
services:
  nginx: 
    build: ./requirements/nginx/.
    image: nginx:42.0
    ports:
      - '443:443'
    links:
      - 'wordpress'
    volumes:
      - 

  db:
    build: ./requirements/mariadb/. 
    image: mariadb:42.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: claire
      MYSQL_PASSWORD: claire123
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:42.0
    build: ./requirements/wordpress/.
    container_name: wordpress
    ports:
      - '9000:9000'
    restart: always
    environment:
      WORDPRESS_DB_HOST : db:3306
      WORDPRESS_DB_USER : claire # = MYSQL_USER
      WORDPRESS_DB_PASSWORD : claire123 # = MYSQL_PASSWORD

networks:
  inception:
volumes:
  data:
  wordpress:
