version: '3.8'
  
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    image: nginx:42.0
    restart: always
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  db:
    build: ./requirements/mariadb/. 
    image: mariadb:42.0
    restart: always
    env_file: 
      - .env
    volumes:
      - data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on:
      - db
    build: ./requirements/wordpress/.
    image: wordpress:42.0
#    ports:
#      - '9000:9000'
    restart: always
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  data:
  wordpress:
