version: '3.8'
  
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    image: nginx:42.0
    container_name: nginx
    restart: always
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb:42.0
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: mysqladmin ping --host=localhost -uroot -p${DB_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress/.
    image: wordpress:42.0
    container_name: wordpress
    restart: always
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      device: /home/cchapon/data/db-data
      o: 'bind'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      device: /home/cchapon/data/web-data
      o: 'bind'
