version: '3.8'

networks:
  inception:
    name: inception
    driver: bridge
  
services:
  nginx:
    image: nginx:42.0
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - '443:443'
#    network: ?

  db:
    image: mariadb:42.0
    build: ./requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped #always
    env_file: ./.env
    environment:
      - 3306:3306 #?
    volumes:
      - type: bind
        source: ../../data/database
        target: /var/lib/mysql

  wordpress:
    depends_on:
      - db
      - nginx #?
    image: wordpress:42.0
    build: ./requirements/wordpress/.
    container_name: wordpress
    ports:
      - 9000:9000 #?
    restart: always
    env_file : ./.env
    volumes:
      - type: bind
        source: ../../data/worpress
        target: /var/www/html
  