version: '3.8'
  
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    image: nginx:42.0
    restart: always
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb/. 
    restart: always
    env_file: 
      - .env
    volumes:
      - data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: mysqladmin ping --host=localhost -p${MYSQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress/.
#    ports:
#      - '9000:9000'
    restart: always
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  data:
  wordpress:
